export const SECTION_TILE = {
  regular: {
    minHeight: 112,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    titleFontSize: 21,
    titleLineHeight: 26,
    subtitleFontSize: 16,
    subtitleLineHeight: 22,
    subtitleMarginTop: 8,
    glowSize: 110,
    glowRadius: 55,
    glowTop: -30,
    glowRight: -25,
    watermarkWidth: 120,
    watermarkHeight: 120,
    watermarkRight: -18,
    watermarkBottom: -22,
  },
  compact: {
    minHeight: 92,
    paddingVertical: 7,
    paddingHorizontal: 9,
    marginBottom: 6,
    titleFontSize: 16,
    titleLineHeight: 19,
    subtitleFontSize: 11,
    subtitleLineHeight: 14,
    subtitleMarginTop: 2,
  },
} as const;
